pipeline {
    agent any

    stages {
        stage('Build') {  /* Build Stage */
            steps {
                script {
                    // Navigate to the simple-counter directory
                    dir('simple-counter') {
                        bat 'npm install'    // Run npm install from within the simple-counter directory
                        bat 'npm run build'  // Build the React app
                    }
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    dir('simple-counter'){
                        bat 'npm run test' // Run tests using Jest
                    }
                }
            }
        }

        stage('Code Quality Analysis') {
            steps {
                script {
                    dir('simple-counter') {
                        bat 'npm run lint'
                    }
                }
            }
        }
        stage('Deploy to Heroku'){
            steps{
                dir('simple-counter'){
                    withCredentials([usernameColonPassword(credentialsId: 'sit753HD', variable: 'PASS')]) {
                        bat 'git checkout -b sit753'
                        bat 'git push https://${PASS}@git.heroku.com/sit753-assignment.git sit753'
                    }
                }
            }
        }
    }
}
