pipeline{
    agent any
    stages {
        stage('Build') {
            steps {
                script {
                    // Install dependencies and build React app
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }
    }
}
