pipeline {
    agent any

    stages {
        stage('Build') {  /* Build Stage */
            steps {
                script {
                    // Navigate to the simple-counter directory
                    dir('simple-counter') {
                        bat 'npm install'    // Run npm install from within the simple-counter directory
                        bat 'npm run build'  // Build the React app
                    }
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    dir('simple-counter'){
                        bat 'npm run test' // Run tests using Jest
                    }
                }
            }
        }
        stage('Code Quality Analysis') {
            steps {
                script {
                    dir('simple-counter') {
                        bat 'npm run lint'
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    // Deploy application using Docker Compose
                    dir('simple-counter') {
                        bat 'docker compose up -d --build'       
                    }
                }
            }
        }
    }
}
